<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('projects')->insert([
            [
                'job_number' => 'zzHsinKt',
                'client_name' => 'zzHsKai',
                'end_user_name' => 'Orin Cassin',
                'project_description' => 'Eum dolor ipsum dicta. Hic perferendis dolorem vel sed soluta. Autem officia iste molestiae libero repudiandae.',
                'project_type' => 'sales',
                'jobsite_location' => 'zz Kaki Bukit',
                'bca_reference_number' => 'zz12345678',
                'status' => 'Ongoing',
                'sms_count' => 5,
                'created_at' => Carbon::parse('2024-06-17 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 10:19:34'),
                'completed_at' => null,
            ],
            [
                'job_number' => 'zzHsiTest',
                'client_name' => 'zKai',
                'end_user_name' => 'Dr. Sarina Bergstrom V',
                'project_description' => 'Illo corporis quia omnis. Animi sapiente in illum nihil voluptas eos. Eum et voluptatem omnis ab aperiam eveniet eveniet.',
                'project_type' => 'sales',
                'jobsite_location' => 'zz Kaki Bukit',
                'bca_reference_number' => 'zz12345678',
                'status' => 'Ongoing',
                'sms_count' => 0,
                'created_at' => Carbon::parse('2024-06-17 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 09:59:53'),
                'completed_at' => null,
            ],
            [
                'job_number' => 'zzHest',
                'client_name' => 'zzHsKai',
                'end_user_name' => 'Prof. Angel Wiegand IV',
                'project_description' => 'Dolorem nulla repellat eos. Quasi mollitia exercitationem fugit error deserunt soluta maxime deleniti. Minima et qui accusantium libero quo itaque. Quas officia quae sunt.',
                'project_type' => 'sales',
                'jobsite_location' => 'zz Kaki Bukit',
                'bca_reference_number' => 'zz12345678',
                'status' => 'Ongoing',
                'sms_count' => 0,
                'created_at' => Carbon::parse('2024-06-17 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 09:59:53'),
                'completed_at' => null,
            ],
            [
                'job_number' => 'znKaiTest',
                'client_name' => 'zzHsai',
                'end_user_name' => null,
                'project_description' => 'Harum omnis officia dolor. Id omnis facere et veritatis et et. Perspiciatis est sint sit perferendis dicta sunt nobis. Ex nihil tenetur aut repudiandae.',
                'project_type' => 'rental',
                'jobsite_location' => 'zz Kaki Bukit',
                'bca_reference_number' => 'zz12345678',
                'status' => 'Ongoing',
                'sms_count' => 5,
                'created_at' => Carbon::parse('2024-06-17 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 09:59:53'),
                'completed_at' => null,
            ],
            [
                'job_number' => 'zV-RTVMRENTAL',
                'client_name' => 'GEOSCAN PTE LTD',
                'end_user_name' => null,
                'project_description' => 'RTVM',
                'project_type' => 'rental',
                'jobsite_location' => '61 KAKIBUKIT AVE 1 SINGAPORE 417943',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-17 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 09:59:53'),
                'completed_at' => null,
            ],
            [
                'job_number' => 'Yuan Zhen 01 (SN2331)',
                'client_name' => 'Yuan Zhen Construction Pte Ltd',
                'end_user_name' => null,
                'project_description' => 'PROPOSED ADDITIONS & ALTERATIONS OF AN EXISTING 2 STOREY FACTORY WITH A 3 STOREY REAR EXTENSION WITH PRODUCTION AND WAREHOUSE ON LOT 01527C MK 07 AT NO. 70 JOO KOON CIRCLE, SINGAPORE 629087 ON LOT (S) 01527C MK07 AT 70 JOO KOON CIRCLE SINGAPORE 629087',
                'project_type' => 'rental',
                'jobsite_location' => '70 Joo Koon Cir, Singapore 629087',
                'bca_reference_number' => 'A1626-00006-2022',
                'status' => 'Completed',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-14 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-28 02:53:30'),
                'completed_at' => Carbon::parse('2024-06-28 02:53:30'),
            ],
            [
                'job_number' => 'Wee-Built 04 (SN2336)',
                'client_name' => 'Wee-Built Pte Ltd',
                'end_user_name' => null,
                'project_description' => 'Real Time Noise Monitoring At 16 Vaughan Road',
                'project_type' => 'rental',
                'jobsite_location' => '16 Vaughan Road',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 1,
                'created_at' => Carbon::parse('2024-06-17 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 09:59:53'),
                'completed_at' => null,
            ],
            [
                'job_number' => 'PJ/5459/06/24 (SN-1663 )',
                'client_name' => 'Antbuildz Pte Ltd',
                'end_user_name' => null,
                'project_description' => 'NOISE MONITORING WORKS FOR PROPOSED RECONSTRUCTION TO A 2-STOREY SEMI- DETACHED DWELLING HOUSE WITH NEW ATTIC ON LOT 05605C MK26 AT 80 FRANKEL AVENUE (BEDOK) - PO NO: PO-0624-5992',
                'project_type' => 'rental',
                'jobsite_location' => '80 Frankel Avenue Singapore 458208',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-16 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-17 09:59:53'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'PJ/5455/06/24 (SN-1868)',
                'client_name' => 'SATO KOGYO (S) PTE LTD',
                'end_user_name' => null,
                'project_description' => 'Instrumentation and Monitoring Works for Proposed Additions and Alterations Involving New Erection of a New Tank Platform and at Existing Single-User Factory Development On Lot 01695T and 04849C MK 13 at 7 Senoko Crescent Singapore 758263',
                'project_type' => 'rental',
                'jobsite_location' => '7 Senoko Crescent Singapore 758263',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-10 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-27 06:40:43'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'acstech12 (SN1485)',
                'client_name' => 'ACS Tech',
                'end_user_name' => 'ACS Tech 12',
                'project_description' => 'Real-Time Noise Monitoring',
                'project_type' => 'sales',
                'jobsite_location' => '74 Jalan Senyum',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-14 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-14 09:59:53'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'acstech10 (SN1558)',
                'client_name' => 'ACS Tech',
                'end_user_name' => 'ACS Tech 10',
                'project_description' => 'Real-Time Noise Monitoring At 12 Lorong G Telok Kurau',
                'project_type' => 'sales',
                'jobsite_location' => '12 Lorong G Telok Kurau',
                'bca_reference_number' => 'A2161-00136-2022',
                'status' => 'Ongoing',
                'sms_count' => 1,
                'created_at' => Carbon::parse('2024-06-10 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-14 09:59:53'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'acstech11(SN1484)',
                'client_name' => 'ACS Tech',
                'end_user_name' => 'ACS Tech 11',
                'project_description' => 'Real Time Noise Monitoring',
                'project_type' => 'sales',
                'jobsite_location' => 'Seletar North Link',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-11 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-11 09:59:53'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'acstech09 (SN1481)',
                'client_name' => 'ACS Tech',
                'end_user_name' => 'ACS Tech 9',
                'project_description' => 'Real Time Noise Monitoring',
                'project_type' => 'sales',
                'jobsite_location' => '350 Siglap Road S(455926)',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 3,
                'created_at' => Carbon::parse('2024-06-14 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-14 09:59:53'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'EKHL PTE LTD 03',
                'client_name' => 'EKHL PTE LTD',
                'end_user_name' => 'EKHL PTE LTD 3',
                'project_description' => 'Real-Time Noise Monitoring',
                'project_type' => 'sales',
                'jobsite_location' => '62 Lucky Heights Singapore 467616',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-11 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-11 09:59:53'),
                'completed_at' => null,
            ],
            [

                'job_number' => 'EKHL PTE LTD 02 (SN1474)',
                'client_name' => 'EKHL PTE LTD',
                'end_user_name' => 'EKHL PTE LTD 2',
                'project_description' => 'Real-Time Noise Monitoring',
                'project_type' => 'sales',
                'jobsite_location' => '12 Hillcrest Rd Singapore 288899',
                'bca_reference_number' => null,
                'status' => 'Ongoing',
                'sms_count' => 2,
                'created_at' => Carbon::parse('2024-06-11 09:59:53'),
                'updated_at' => Carbon::parse('2024-06-27 07:05:35'),
                'completed_at' => null,
            ],
        ]);
    }
}